apache2:
    image: php:7-apache
    ports:
        - "8080:80"
    volumes:
        - ./files/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
        - ../code/phpbenchmarks-symfony-helloworld:/var/www/html
